# Generated by Django 5.2.7 on 2026-02-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistltem',
            name='edit',
            field=models.BooleanField(default=False),
        ),
    ]
