# Generated by Django 6.0.2 on 2026-02-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todolistltem_edit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoListLtem',
            new_name='TodoListItem',
        ),
    ]
